#!/bin/bash -l

COMPILER=${COMPILER:-gcc}
echo "revno: $GIT_COMMIT"
export LANG=${LANG:-C}

while getopts "hj:n-" optchar; do
  case "${optchar}" in
    j) export pjobs="-j${OPTARG}" ;;
    n) no_ccache=true ;;
    -) break ;;
  esac
done
shift $((OPTIND -1))

case $1 in
  gcc*|clang*|icc*) COMPILER=$1; shift ;;
esac

case "$COMPILER" in
  gcc*) CC="gcc${COMPILER#gcc}"; CXX="g++${COMPILER#gcc}";;
  clang*) CC="clang${COMPILER#clang}"; CXX="clang++${COMPILER#clang}";;
  icc) CC="icc"; CXX="icpc";;
  *) echo "Unknown COMPILER set, aborting"; exit 1;;
esac

for cc in $(type -path ccache) /usr/bin/ccache /usr/local/bin/ccache
do
  test -x $cc && ccache_bin="$cc "
done

if [ "$COMPILER" != "icc" -a -z "${no_ccache}" ]
then
   CC="${ccache_bin}${CC}"
   CXX="${ccache_bin}${CXX}"
fi
export CC CXX

# custom command paths 
for extrapath in \
  /home/jenkins/bin \
  /opt/rh/devtoolset-2/root/usr/bin
do
  test -d "$extrapath" && export PATH="$extrapath:$PATH"
done

echo "***** Start time: $(date) *****"
./test-builds.sh $@
result=$?
if [ $result -gt 0 ] && grep -q 'You should only need it if you modified' btlayer-00-default.log ; then
  (cd libltdl; autoreconf -fi)
  time ./test-builds.sh $@
else
  exit $result
fi
echo "***** End time: $(date) *****"
