#!/bin/sh
helpmsg=<<_EOF
 configuration file: ~/.jenkins.rc.
 it's a shell script, must contain two variables setting:
 credentials=user:password
 slavename=...
 sleeptime=... (optional, default=60)
on BSD:
  remember to set and export 
AUTOCONF_VERSION=2.61
AUTOMAKE_VERSION=1.10
export AUTOCONF_VERSION AUTOMAKE_VERSION
_EOF

if [ `id -u` -eq 0 ]; then
  exec su jenkins -c "$0 $@"
fi

if [ -e $HOME/.jenkins.rc ]; then
  . ~/.jenkins.rc
else
  echo "$helpmsg"
  exit 1
fi

CCACHE_COMPRESS=1
export CCACHE_COMPRESS

do_start_jenkins() {
	test -e ~/.jenkins.rc && . ~/.jenkins.rc
	curl http://build.squid-cache.org/jnlpJars/slave.jar >slave.jar && \
	java -jar slave.jar -jnlpUrl http://build.squid-cache.org/computer/$slavename/slave-agent.jnlp -secret $secret >start-jenkins.log 2>&1 
}

cd $HOME
(\
while do_start_jenkins; do
  if [ -e $HOME/jenkins.stop ]; then
    rm $HOME/jenkins.stop
    exit 0
  fi
  sleep 60
done
)&
