#!/bin/bash
# args: --force, --build
# compilers: --clang, --icc

read -d '' helpmsg <<_EOF
options: dir, force, build, clang, icc, no-ccache, log=file,
         ring, parallel=#, clean, revno, no-opt, ecap, help
_EOF

opt=$(getopt --longoptions clean,revno:,force,build,clang,icc,no-ccache,no-opt,log:,parallel:,help,ecap,ring,pass:,dir: --options fbcinl:p:hrd: -- "$@")
if [ $? != 0 ] ; then echo "Problem parsing options; terminating" >&2 ; exit 1 ; fi
eval set -- "$opt"
#default
CC=gcc
CXX=g++

while true; do
  case "$1" in
    --ecap) ECAP_CONFIGURE_FLAGS="--enable-ecap=yes"; shift;;
    --no-opt)
      export CFLAGS="$CFLAGS -O0 -g"
      export CXXFLAGS="$CXXFLAGS -O0 -g"
      shift ;;
    -f|--force) force_bootstrap="yes"; shift;;
    -b|--build) do_build="yes"; shift;;
    -c|--clang) CC="clang"; CXX="clang++"; shift;;
    -i|--icc) CC="icc"; CXX="icpc"; shift;;
    -n|--no-ccache) ccache="no"; export CCACHE_DISABLE=1; shift;;
    -l|--log) logfile="$2" ; shift 2;;
    -h|--help) echo $helpmsg; exit 0;;
    -r|--ring) do_ring=true; shift;;
    -p|--parallel) parallel="-j $2 "; shift 2;;
    -d|--dir) builddir="$2 "; shift 2;;
    --pass) extraargs="$2"; shift 2;;
    --clean) do_clean=true; shift;;
    --revno) revno="$2"; shift 2;;
    --) shift; break;;
    *) echo "internal error"; exit 1;;
  esac
done
if [ -n $logfile ]; then
  exec > >(tee $logfile)
  exec 2>&1
fi

DISTCHECK_CONFIGURE_FLAGS=" \
        --enable-loadable-modules \
        --enable-gnuregex \
        --enable-optimizations \
        --enable-inline \
        --enable-debug-cbdata \
        --enable-xmalloc-statistics \
        --enable-async-io \
        --enable-disk-io \
        --enable-removal-policies \
        --enable-icmp \
        --enable-delay-pools \
        --enable-icap-client \
        --enable-useragent-log \
        --enable-referer-log \
        --enable-wccp \
        --enable-wccpv2 \
        --enable-kill-parent-hack \
        --enable-snmp \
        --enable-cachemgr-hostname \
        --enable-eui \
        --enable-htcp \
        --enable-ssl \
        --with-openssl \
        --enable-forw-via-db \
        --enable-cache-digests \
        --enable-poll \
        --enable-select \
        --enable-http-violations \
        --enable-ipfw-transparent \
        --enable-leakfinder \
        --enable-follow-x-forwarded-for \
        --enable-ident-lookups \
        --enable-internal-dns \
        --enable-default-hostsfile \
        --enable-auth \
        --enable-basic-auth-helpers \
        --enable-ntlm-auth-helpers \
        --enable-negotiate-auth-helpers \
        --enable-digest-auth-helpers \
        --enable-ntlm-fail-open \
        --enable-external-acl-helpers \
        --enable-url-rewrite-helpers \
        --enable-mempools \
        --enable-unlinkd \
        --enable-stacktraces \
        --enable-vary \
        --enable-x-accelerator-vary \
        --enable-ipv6 \
        --enable-auto-locale \
        --enable-translation \
        --enable-zph-qos \
        --enable-esi \
        --with-aio \
        --with-build-environment=default \
        --with-dl \
        --with-dns-cname \
        --with-gnu-ld \
        --with-ipv6-split-stack \
        --with-large-files \
        --with-pic \
        --with-pthreads \
        --disable-arch-native \
        "

if [ "x$ccache" != "xno" ]; then
  CC="ccache $CC"
  CXX="ccache $CXX"
fi

#clean
if [ -n "$do_clean" -a -f test-builds.sh ]; then
  if test -d btlayer-00-bootstrap; then
    chmod -R u+w btlayer*; rm -rf btlayer*
  fi
  touch foo.o
  find . \( -name \*.[oa] -o -name Makefile.in -o -name autom4te.cache -o -name cfgaux -o -name configure -o -name aclocal.m4 -o -name \*~ -o -name autoconf.h.in -o -name config.h.in -o -name \*.lo -o -name .dirstamp \) -type f -delete -print
  for dir in autom4te.cache cfgaux lib/libTrie/autom4te.cache lib/libTrie/cfgaux libltdl lib/libTrie/libltdl; do
    test -d $dir && rm  -rf $dir
  done
  bzr clean-tree --force
fi

if [ -n "$revno" ]; then
  echo "Switching to revision $revno"
  bzr revert -r$revno
fi

#macos hacks
if [ "x$(uname -s)" = "xDarwin" ]; then
  export CPPFLAGS="$CPPFLAGS -I/opt/local/include"
  export LDFLAGS="$LDFLAGS -lresolv -lssl -lcrypto"
  export FS_CONFIGURE_FLAGS="--enable-storeio=ufs,aufs,diskd"
fi

if [ ! -e ./configure -o "x$force_bootstrap" = "xyes" ]; then
  ./bootstrap.sh
fi

if [ -n "$builddir" ]; then
  if [ ! -d "$builddir" ]; then
    echo "Creating build dir $builddir"
    mkdir -p $builddir
  fi
  srcdir=$(pwd)
  cd $builddir
fi

test -n "$CC" && export CC CXX
${srcdir:=.}/configure --cache-file=/tmp/config-${CC#ccache }.cache $DISTCHECK_CONFIGURE_FLAGS $FS_CONFIGURE_FLAGS --prefix=$HOME/squid/install --without-netfilter-conntrack --disable-build-info $extraargs

if [ $? -eq 0 -a "x$do_build" = "xyes" ]; then
  make ${parallel} all && make ${parallel} check
fi

if [ "$do_ring" = "true" ]; then
  echo -n ""
fi
