#!/bin/bash -xl

COMPILER=${COMPILER:-gcc}
echo "revno: $GIT_COMMIT"
LANG=${LANG:-C}

case $1 in
	gcc*|clang*|icc*) COMPILER=$1; shift ;;
	*) ;;
esac

case "$COMPILER" in
  gcc) CC="gcc"; CXX="g++";;
  clang) CC="clang"; CXX="clang++";;
  icc) CC="icc"; CXX="icpc";;
  *) echo "Unknown COMPILER set, aborting"; exit 1;;
esac

for cc in $(type -path ccache) /usr/bin/ccache /usr/local/bin/ccache
do
	test -x $cc && ccache_bin="$cc "
done

if [ "$COMPILER" != "icc" ]
then
   CC="${ccache_bin}${CC}"
   CXX="${ccache_bin}${CXX}"
fi
export CC CXX

# custom command paths 
for extrapath in \
	/home/jenkins/bin \
	/opt/rh/devtoolset-2/root/usr/bin
do
	test -d "$extrapath" && export PATH="$extrapath:$PATH"
done

time ./test-builds.sh $@
result=$?
if [ $result -gt 0 ] && grep -q 'You should only need it if you modified' btlayer-00-default.log ; then
	(cd libltdl; autoreconf -fi)
	time ./test-builds.sh $@
else
	exit $result
fi
