#!/bin/sh
helpmsg=<<_EOF
 configuration file: ~/.jenkins.rc.
 it's a shell script, must contain two variables setting:
 credentials=user:password
 slavename=...
_EOF

if [ `id -u` -eq 0 ]; then
  exec su jenkins -c "$0 $@"
fi

if [ ! -e $HOME/.jenkins.rc ]; then
  . ~/.jenkins.rc
else
  echo $helpmsg
fi

CCACHE_COMPRESS=1
export CCACHE_COMPRESS

AUTOCONF_VERSION=2.61
AUTOMAKE_VERSION=1.10
export AUTOCONF_VERSION AUTOMAKE_VERSION

cd $HOME
(\
while sleep 60; do
	/usr/local/bin/curl http://build.squid-cache.org/jnlpJars/slave.jar >slave.jar
	java -jar slave.jar -jnlpUrl http://build.squid-cache.org/computer/$slavename/slave-agent.jnlp -jnlpCredentials $credentials >start-jenkins.log 2>&1 
done
)&
