#!/bin/bash

for dir in *
do
	if [ ! -d "$dir" ]; then
		continue
	fi
	if [ ! -d "$dir/.bzr" ]; then
		continue
	fi
  echo "*********** starting $dir **********"
	(cd $dir; bzr update)
  echo "************* done $dir ************"
done
