#!/bin/bash

list() {
    docker search 'squidcache' | grep "^squidcache/.*-${ARCH}-" | awk '{print $1}' | sed "s/.*-${ARCH}-//" | sort
}

help() {
    cat <<_EOF
$0 -l : list images
$0 -o os [-s (stable)] [-u user (current uid)] [-- command (/bin/bash -l)]
_EOF
}

ARCH=`uname -m`
DEFAULT_UID=`id -u`
while getopts "so:hu:l-" optchar; do
    case "${optchar}" in
    u) user=${OPTARG};;
    l) list; exit 0;;
    h) help; exit 0;;
    o) os=${OPTARG} ;;
    s) version="stable" ;;
    -) break;;
    esac
done
shift $((OPTIND -1))
if [ $# -gt 0 ] ; then
    command=$@
else
    command="/bin/bash -l"
fi
if [ -z "$os" ]; then
    echo "you need to specify an OS"
    help
    exit 1
fi

exec docker run -ti --rm -v"$HOME:$HOME" -w"$PWD" \
    -u ${user:-$DEFAULT_UID} \
    -h "i-${os}" \
    squidcache/buildfarm-${ARCH}-${os}:${version:-latest} \
    $command
