#!/bin/bash

configsdir=`dirname $0`/configs

detect_commands() {
    INSTALL=install
    test -n "`which ginstall`" && INSTALL=ginstall
}

# args: config to be installed (from configs), and where to
install_config() {
	test -f $2 && echo "$1 already installed to $2"
	read -n1 -p "install $1? [y/f/*]" q ; echo
	case $q in
		f|F) $INSTALL -D -v $configsdir/$1 $2;;
		y|Y) test -f $2 || $INSTALL -D -v $configsdir/$1 $2;;
		*) : ;;
	esac
}

detect_commands
install_config gitconfig ~/.gitconfig
install_config gitignore ~/.gitignore
install_config tmux.conf ~/.tmux.conf
install_config gdbinit ~/.config/gdb/init
sed -i 's/_AT_PLACEHOLDER_/@/' ~/.gitconfig

test -n "`which vim`" && git config --global core.editor vim

install_config vimrc ~/.vimrc
mkdir -v -m 700 ~/.ssh
install_config ssh-config ~/.ssh/config

install_config bash_profile ~/.bash_profile
#test -e ~/.bashrc && mv ~/.bashrc ~/.bashrc.local
install_connfig bashrc ~/.bashrc.local
echo 'test -e ~/.bashrc.local && . ~/.bashrc.local' >>~/.bashrc

if test -n "`which gpg`"; then
    gpg --decrypt $configsdir/gnupg.tar.gpg | (cd $HOME; tar xvf -)
else
    touch ~/00-please-intall-gpg-and-keyring
fi

if [ -x /usr/bin/systemctl ]; then
	echo "preparing ssh-agent service"
	install_config ssh-agent.service ~/.config/systemd/user/ssh-agent.service
    read -n1 -p "Activate systemd-based ssh-agent?" q
    case $q in
        y) systemctl --user enable ssh-agent; systemctl --user start ssh-agent;;
        *) : ;;
    esac
fi
